### ISSUE TITLE
Rename this repo to "classic"

### ISSUE THREAD

**Issue by ashawley** [dispatch/classic#105]
The new repo is called "reboot", but not every one finds it.

**Comment by farmdawgnation** [comment]
I will look at renaming this one classic if there's no objection from others. Don't know about renaming the new one dispatch/reboot, tbh, but will consider. =)

**Comment by ashawley** [comment]
Thanks, Matt.  Github does a pretty job of redirecting old names to new names.  This project has been so quiet for so long, I don't think we'll have to tell a lot of people.  Maybe community-builds, and that's it.

**Comment by farmdawgnation** [comment]
This has been done.
